version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  reviewers:
  - jrmash
  assignees:
  - jrmash
