name: "ShiftLeft Scan"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Initialize JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    
    - name: Build
      run: ./gradlew compileJava
    - name: Perform Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCAN_AUTO_BUILD: true
      with:
        output: reports
        type: credscan,depscan,java
    - name: Upload Report
      uses: actions/upload-artifact@v1.0.0
      with:
        name: shiftleft-scan-reports
        path: reports
