name: SonarCloud Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Initialize JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    
    - name: Build
      run: ./gradlew compileJava
    - name: Perform Scan
      uses: SonarSource/sonarcloud-github-action@v1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
